export interface Software {
  id: string
  name: string
  version: string
  category: string
  description: string
  longDescription: string
  developer: string
  releaseDate: string
  fileSize: string
  downloads: number
  rating: number
  license: string
  operatingSystem: string[]
  requirements: string[]
  features: string[]
  downloadLink: string
  screenshots: string[]
  tags: string[]
}

export const softwareData: Software[] = [
  {
    id: "adobe-photoshop-2024",
    name: "Adobe Photoshop 2024",
    version: "25.0",
    category: "Graphics & Design",
    description: "Professional image editing and graphic design software",
    longDescription:
      "Adobe Photoshop is the industry-standard software for digital image processing and editing. With powerful tools for photo retouching, compositing, and digital painting, Photoshop enables creative professionals to bring their visions to life.",
    developer: "Adobe Inc.",
    releaseDate: "2024-01-15",
    fileSize: "2.8 GB",
    downloads: 1250000,
    rating: 4.8,
    license: "Commercial",
    operatingSystem: ["Windows 10/11", "macOS 12+"],
    requirements: ["8GB RAM minimum", "4GB GPU VRAM", "10GB free disk space"],
    features: [
      "AI-powered selection tools",
      "Neural filters",
      "Cloud document sync",
      "Content-aware fill",
      "3D editing capabilities",
    ],
    downloadLink: "/downloads/adobe-photoshop-2024",
    screenshots: ["/photoshop-interface.jpg"],
    tags: ["photo editing", "design", "creative", "professional"],
  },
  {
    id: "vlc-media-player",
    name: "VLC Media Player",
    version: "3.0.20",
    category: "Multimedia",
    description: "Free and open-source cross-platform multimedia player",
    longDescription:
      "VLC is a free and open source cross-platform multimedia player that plays most multimedia files, DVDs, Audio CDs, VCDs, and various streaming protocols.",
    developer: "VideoLAN",
    releaseDate: "2024-02-10",
    fileSize: "42 MB",
    downloads: 3500000,
    rating: 4.9,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "100MB free disk space"],
    features: [
      "Plays all formats",
      "Hardware acceleration",
      "Subtitle support",
      "Streaming capabilities",
      "Audio/video filters",
    ],
    downloadLink: "/downloads/vlc-media-player",
    screenshots: ["/vlc-media-player.jpg"],
    tags: ["video player", "media", "free", "open source"],
  },
  {
    id: "microsoft-office-2024",
    name: "Microsoft Office 2024",
    version: "16.0",
    category: "Productivity",
    description: "Complete office suite with Word, Excel, PowerPoint, and more",
    longDescription:
      "Microsoft Office 2024 is the latest version of the world's most popular productivity suite, featuring Word, Excel, PowerPoint, Outlook, and more with AI-powered features.",
    developer: "Microsoft Corporation",
    releaseDate: "2024-01-20",
    fileSize: "4.2 GB",
    downloads: 2800000,
    rating: 4.7,
    license: "Commercial",
    operatingSystem: ["Windows 10/11", "macOS 12+"],
    requirements: ["4GB RAM", "10GB free disk space", "Internet connection"],
    features: [
      "AI writing assistant",
      "Real-time collaboration",
      "Cloud storage integration",
      "Advanced data analysis",
      "Professional templates",
    ],
    downloadLink: "/downloads/microsoft-office-2024",
    screenshots: ["/microsoft-office-interface.jpg"],
    tags: ["productivity", "office", "documents", "spreadsheets"],
  },
  {
    id: "google-chrome",
    name: "Google Chrome",
    version: "122.0",
    category: "Internet & Network",
    description: "Fast, secure, and free web browser",
    longDescription:
      "Google Chrome is a fast, secure, and free web browser built for the modern web. Chrome syncs bookmarks across all your devices, fills out forms automatically, and more.",
    developer: "Google LLC",
    releaseDate: "2024-02-20",
    fileSize: "95 MB",
    downloads: 5200000,
    rating: 4.6,
    license: "Freeware",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "350MB free disk space"],
    features: ["Fast browsing", "Built-in security", "Extensions support", "Cross-device sync", "Incognito mode"],
    downloadLink: "/downloads/google-chrome",
    screenshots: ["/google-chrome-browser.jpg"],
    tags: ["browser", "internet", "web", "google"],
  },
  {
    id: "winrar",
    name: "WinRAR",
    version: "6.24",
    category: "Utilities",
    description: "Powerful archive manager for Windows",
    longDescription:
      "WinRAR is a powerful archive manager providing complete support for RAR and ZIP archives and unpacking CAB, ARJ, LZH, TAR, GZ, UUE, BZ2, JAR, ISO, 7Z, XZ, Z archives.",
    developer: "RARLAB",
    releaseDate: "2024-01-05",
    fileSize: "3.2 MB",
    downloads: 1800000,
    rating: 4.5,
    license: "Shareware",
    operatingSystem: ["Windows"],
    requirements: ["1GB RAM", "10MB free disk space"],
    features: [
      "High compression ratio",
      "Password protection",
      "Multi-volume archives",
      "Self-extracting archives",
      "Repair damaged archives",
    ],
    downloadLink: "/downloads/winrar",
    screenshots: ["/winrar-interface.jpg"],
    tags: ["compression", "archive", "zip", "utilities"],
  },
  {
    id: "ccleaner",
    name: "CCleaner",
    version: "6.20",
    category: "Utilities",
    description: "System optimization and privacy tool",
    longDescription:
      "CCleaner is a system optimization, privacy and cleaning tool. It removes unused files from your system allowing Windows to run faster and freeing up valuable hard disk space.",
    developer: "Piriform",
    releaseDate: "2024-02-01",
    fileSize: "45 MB",
    downloads: 2100000,
    rating: 4.4,
    license: "Freemium",
    operatingSystem: ["Windows", "macOS"],
    requirements: ["2GB RAM", "100MB free disk space"],
    features: ["Disk cleanup", "Registry cleaner", "Privacy protection", "Startup manager", "Browser cleaning"],
    downloadLink: "/downloads/ccleaner",
    screenshots: ["/ccleaner-interface.jpg"],
    tags: ["cleaner", "optimization", "privacy", "utilities"],
  },
  {
    id: "obs-studio",
    name: "OBS Studio",
    version: "30.1",
    category: "Multimedia",
    description: "Free and open-source streaming and recording software",
    longDescription:
      "OBS Studio is free and open source software for video recording and live streaming. Stream to Twitch, YouTube and many other providers or record your own videos with high quality H264 / AAC encoding.",
    developer: "OBS Project",
    releaseDate: "2024-02-15",
    fileSize: "120 MB",
    downloads: 1950000,
    rating: 4.8,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["4GB RAM", "DirectX 10.1 compatible GPU", "500MB free disk space"],
    features: [
      "High performance real-time video/audio capturing",
      "Scene composition",
      "Unlimited sources",
      "VST plugin support",
      "Powerful API",
    ],
    downloadLink: "/downloads/obs-studio",
    screenshots: ["/obs-studio-interface.jpg"],
    tags: ["streaming", "recording", "video", "free"],
  },
  {
    id: "audacity",
    name: "Audacity",
    version: "3.4.2",
    category: "Multimedia",
    description: "Free, open-source audio editing software",
    longDescription:
      "Audacity is an easy-to-use, multi-track audio editor and recorder for Windows, macOS, GNU/Linux and other operating systems. It's free, open source software.",
    developer: "Audacity Team",
    releaseDate: "2024-01-25",
    fileSize: "28 MB",
    downloads: 1650000,
    rating: 4.6,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "100MB free disk space"],
    features: ["Recording", "Import/Export", "Sound quality", "Plugins", "Effects"],
    downloadLink: "/downloads/audacity",
    screenshots: ["/audacity-audio-editor.jpg"],
    tags: ["audio", "editing", "recording", "free"],
  },
  {
    id: "7-zip",
    name: "7-Zip",
    version: "23.01",
    category: "Utilities",
    description: "Free and open-source file archiver",
    longDescription:
      "7-Zip is a free and open-source file archiver with a high compression ratio. It supports multiple formats and provides strong AES-256 encryption.",
    developer: "Igor Pavlov",
    releaseDate: "2024-01-10",
    fileSize: "1.5 MB",
    downloads: 2900000,
    rating: 4.9,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "Linux"],
    requirements: ["512MB RAM", "5MB free disk space"],
    features: [
      "High compression ratio",
      "Strong AES-256 encryption",
      "Self-extracting capability",
      "Integration with Windows Shell",
      "Powerful File Manager",
    ],
    downloadLink: "/downloads/7-zip",
    screenshots: ["/7zip-file-manager.jpg"],
    tags: ["compression", "archive", "free", "open source"],
  },
  {
    id: "notepad-plus-plus",
    name: "Notepad++",
    version: "8.6.2",
    category: "Development",
    description: "Free source code editor and Notepad replacement",
    longDescription:
      "Notepad++ is a free source code editor and Notepad replacement that supports several languages. Running in the MS Windows environment, its use is governed by GNU General Public License.",
    developer: "Don Ho",
    releaseDate: "2024-02-05",
    fileSize: "4.5 MB",
    downloads: 2200000,
    rating: 4.8,
    license: "Free/Open Source",
    operatingSystem: ["Windows"],
    requirements: ["1GB RAM", "10MB free disk space"],
    features: ["Syntax highlighting", "Auto-completion", "Multi-document", "Macro recording", "Plugin support"],
    downloadLink: "/downloads/notepad-plus-plus",
    screenshots: ["/notepad---code-editor.jpg"],
    tags: ["editor", "code", "development", "free"],
  },
  {
    id: "visual-studio-code",
    name: "Visual Studio Code",
    version: "1.87",
    category: "Development",
    description: "Free code editor with built-in debugging and Git support",
    longDescription:
      "Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop. It comes with built-in support for JavaScript, TypeScript and Node.js.",
    developer: "Microsoft Corporation",
    releaseDate: "2024-02-28",
    fileSize: "85 MB",
    downloads: 4100000,
    rating: 4.9,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "200MB free disk space"],
    features: ["IntelliSense", "Debugging", "Git integration", "Extensions", "Integrated terminal"],
    downloadLink: "/downloads/visual-studio-code",
    screenshots: ["/vscode-editor-interface.jpg"],
    tags: ["editor", "code", "development", "microsoft"],
  },
  {
    id: "discord",
    name: "Discord",
    version: "0.0.309",
    category: "Communication",
    description: "Voice, video, and text communication platform",
    longDescription:
      "Discord is the easiest way to talk over voice, video, and text. Talk, chat, hang out, and stay close with your friends and communities.",
    developer: "Discord Inc.",
    releaseDate: "2024-02-22",
    fileSize: "95 MB",
    downloads: 3800000,
    rating: 4.7,
    license: "Freeware",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "200MB free disk space"],
    features: ["Voice channels", "Video calls", "Screen sharing", "Server communities", "Direct messaging"],
    downloadLink: "/downloads/discord",
    screenshots: ["/discord-app-interface.jpg"],
    tags: ["chat", "voice", "communication", "gaming"],
  },
  {
    id: "spotify",
    name: "Spotify",
    version: "1.2.31",
    category: "Multimedia",
    description: "Digital music streaming service",
    longDescription:
      "Spotify is a digital music service that gives you access to millions of songs, podcasts, and videos from artists all over the world.",
    developer: "Spotify AB",
    releaseDate: "2024-02-18",
    fileSize: "120 MB",
    downloads: 4500000,
    rating: 4.6,
    license: "Freemium",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "250MB free disk space"],
    features: ["Millions of songs", "Personalized playlists", "Podcast support", "Offline mode", "Cross-device sync"],
    downloadLink: "/downloads/spotify",
    screenshots: ["/spotify-music-app.jpg"],
    tags: ["music", "streaming", "audio", "entertainment"],
  },
  {
    id: "zoom",
    name: "Zoom",
    version: "5.17.5",
    category: "Communication",
    description: "Video conferencing and online meeting platform",
    longDescription:
      "Zoom is a cloud-based video conferencing service you can use to virtually meet with others - either by video or audio-only or both.",
    developer: "Zoom Video Communications",
    releaseDate: "2024-02-12",
    fileSize: "75 MB",
    downloads: 3200000,
    rating: 4.5,
    license: "Freemium",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["4GB RAM", "200MB free disk space"],
    features: ["HD video meetings", "Screen sharing", "Recording", "Virtual backgrounds", "Breakout rooms"],
    downloadLink: "/downloads/zoom",
    screenshots: ["/zoom-meeting-interface.png"],
    tags: ["video", "conferencing", "meetings", "communication"],
  },
  {
    id: "gimp",
    name: "GIMP",
    version: "2.10.36",
    category: "Graphics & Design",
    description: "Free and open-source image editor",
    longDescription:
      "GIMP is a cross-platform image editor available for GNU/Linux, macOS, Windows and more operating systems. It is free software, you can change its source code and distribute your changes.",
    developer: "GIMP Team",
    releaseDate: "2024-01-30",
    fileSize: "280 MB",
    downloads: 1750000,
    rating: 4.6,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "500MB free disk space"],
    features: ["Photo retouching", "Image composition", "Image authoring", "Customizable interface", "Plugin support"],
    downloadLink: "/downloads/gimp",
    screenshots: ["/gimp-image-editor.jpg"],
    tags: ["image editing", "graphics", "free", "open source"],
  },
  {
    id: "blender",
    name: "Blender",
    version: "4.1",
    category: "Graphics & Design",
    description: "Free and open-source 3D creation suite",
    longDescription:
      "Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking.",
    developer: "Blender Foundation",
    releaseDate: "2024-03-01",
    fileSize: "320 MB",
    downloads: 1450000,
    rating: 4.8,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["8GB RAM", "4GB GPU VRAM", "1GB free disk space"],
    features: ["3D modeling", "Animation", "Rendering", "Simulation", "Video editing"],
    downloadLink: "/downloads/blender",
    screenshots: ["/blender-3d-software.jpg"],
    tags: ["3d", "modeling", "animation", "free"],
  },
  {
    id: "teamviewer",
    name: "TeamViewer",
    version: "15.51",
    category: "Utilities",
    description: "Remote access and support software",
    longDescription:
      "TeamViewer is a comprehensive, remote access, remote control and remote support solution that works with almost every desktop and mobile platform.",
    developer: "TeamViewer AG",
    releaseDate: "2024-02-08",
    fileSize: "45 MB",
    downloads: 1900000,
    rating: 4.4,
    license: "Freemium",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "100MB free disk space"],
    features: ["Remote control", "File transfer", "VPN", "Meeting", "Cross-platform"],
    downloadLink: "/downloads/teamviewer",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["remote", "support", "access", "utilities"],
  },
  {
    id: "malwarebytes",
    name: "Malwarebytes",
    version: "4.6.5",
    category: "Security",
    description: "Anti-malware and security software",
    longDescription:
      "Malwarebytes protects you against malware, ransomware, and other advanced online threats that have made antivirus obsolete and ineffective.",
    developer: "Malwarebytes Inc.",
    releaseDate: "2024-02-14",
    fileSize: "85 MB",
    downloads: 2300000,
    rating: 4.7,
    license: "Freemium",
    operatingSystem: ["Windows", "macOS"],
    requirements: ["2GB RAM", "250MB free disk space"],
    features: [
      "Real-time protection",
      "Ransomware protection",
      "Web protection",
      "Exploit protection",
      "Malware removal",
    ],
    downloadLink: "/downloads/malwarebytes",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["security", "antivirus", "malware", "protection"],
  },
  {
    id: "dropbox",
    name: "Dropbox",
    version: "193.4.5753",
    category: "Utilities",
    description: "Cloud storage and file synchronization service",
    longDescription:
      "Dropbox is a file hosting service that offers cloud storage, file synchronization, personal cloud, and client software.",
    developer: "Dropbox Inc.",
    releaseDate: "2024-02-25",
    fileSize: "150 MB",
    downloads: 2700000,
    rating: 4.5,
    license: "Freemium",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "500MB free disk space"],
    features: ["File sync", "Cloud storage", "File sharing", "Collaboration", "Version history"],
    downloadLink: "/downloads/dropbox",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["cloud", "storage", "sync", "backup"],
  },
  {
    id: "steam",
    name: "Steam",
    version: "2024.02.15",
    category: "Gaming",
    description: "Digital distribution platform for video games",
    longDescription:
      "Steam is a video game digital distribution service and storefront by Valve. It provides game updates automatically, community features, and cloud saves.",
    developer: "Valve Corporation",
    releaseDate: "2024-02-15",
    fileSize: "2 MB",
    downloads: 4800000,
    rating: 4.8,
    license: "Freeware",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["1GB RAM", "5GB free disk space"],
    features: ["Game library", "Auto-updates", "Cloud saves", "Community features", "Workshop"],
    downloadLink: "/downloads/steam",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["gaming", "games", "platform", "entertainment"],
  },
  {
    id: "handbrake",
    name: "HandBrake",
    version: "1.7.3",
    category: "Multimedia",
    description: "Open-source video transcoder",
    longDescription:
      "HandBrake is a tool for converting video from nearly any format to a selection of modern, widely supported codecs.",
    developer: "HandBrake Team",
    releaseDate: "2024-01-28",
    fileSize: "18 MB",
    downloads: 1350000,
    rating: 4.7,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "100MB free disk space"],
    features: ["Video conversion", "Batch processing", "Presets", "Video filters", "Subtitle support"],
    downloadLink: "/downloads/handbrake",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["video", "converter", "transcoder", "free"],
  },
  {
    id: "putty",
    name: "PuTTY",
    version: "0.80",
    category: "Development",
    description: "Free SSH and telnet client",
    longDescription:
      "PuTTY is a free implementation of SSH and Telnet for Windows and Unix platforms, along with an xterm terminal emulator.",
    developer: "Simon Tatham",
    releaseDate: "2024-01-18",
    fileSize: "3 MB",
    downloads: 1550000,
    rating: 4.6,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "Linux"],
    requirements: ["512MB RAM", "5MB free disk space"],
    features: ["SSH client", "Telnet client", "Serial console", "Raw socket", "Key generation"],
    downloadLink: "/downloads/putty",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["ssh", "terminal", "development", "free"],
  },
  {
    id: "filezilla",
    name: "FileZilla",
    version: "3.66.5",
    category: "Internet & Network",
    description: "Free FTP solution",
    longDescription:
      "FileZilla is a fast and reliable cross-platform FTP, FTPS and SFTP client with lots of useful features and an intuitive graphical user interface.",
    developer: "FileZilla Project",
    releaseDate: "2024-02-03",
    fileSize: "15 MB",
    downloads: 1680000,
    rating: 4.5,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["1GB RAM", "50MB free disk space"],
    features: ["FTP/FTPS/SFTP support", "Drag and drop", "Directory comparison", "Remote file editing", "Bookmarks"],
    downloadLink: "/downloads/filezilla",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["ftp", "file transfer", "network", "free"],
  },
  {
    id: "inkscape",
    name: "Inkscape",
    version: "1.3.2",
    category: "Graphics & Design",
    description: "Free and open-source vector graphics editor",
    longDescription:
      "Inkscape is professional quality vector graphics software which runs on Linux, Mac OS X and Windows desktop computers.",
    developer: "Inkscape Project",
    releaseDate: "2024-01-22",
    fileSize: "180 MB",
    downloads: 1420000,
    rating: 4.6,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "500MB free disk space"],
    features: ["Vector drawing", "Text tool", "Bezier curves", "SVG format", "Extensions"],
    downloadLink: "/downloads/inkscape",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["vector", "graphics", "design", "free"],
  },
  {
    id: "virtualbox",
    name: "VirtualBox",
    version: "7.0.14",
    category: "Utilities",
    description: "Free and open-source virtualization software",
    longDescription:
      "VirtualBox is a powerful x86 and AMD64/Intel64 virtualization product for enterprise as well as home use.",
    developer: "Oracle Corporation",
    releaseDate: "2024-02-06",
    fileSize: "105 MB",
    downloads: 1850000,
    rating: 4.7,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["4GB RAM", "30GB free disk space"],
    features: ["Virtual machines", "Snapshots", "Shared folders", "USB support", "Remote display"],
    downloadLink: "/downloads/virtualbox",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["virtualization", "vm", "utilities", "free"],
  },
  {
    id: "qbittorrent",
    name: "qBittorrent",
    version: "4.6.3",
    category: "Internet & Network",
    description: "Free and open-source BitTorrent client",
    longDescription:
      "qBittorrent is a free and open-source BitTorrent client that aims to provide an open-source software alternative to µTorrent.",
    developer: "qBittorrent Project",
    releaseDate: "2024-02-11",
    fileSize: "32 MB",
    downloads: 2050000,
    rating: 4.8,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["1GB RAM", "100MB free disk space"],
    features: ["Torrent search", "Sequential downloading", "RSS support", "IP filtering", "Web UI"],
    downloadLink: "/downloads/qbittorrent",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["torrent", "download", "p2p", "free"],
  },
  {
    id: "libreoffice",
    name: "LibreOffice",
    version: "24.2",
    category: "Productivity",
    description: "Free and open-source office suite",
    longDescription:
      "LibreOffice is a powerful and free office suite, used by millions of people around the world. Its clean interface and feature-rich tools help you unleash your creativity.",
    developer: "The Document Foundation",
    releaseDate: "2024-02-29",
    fileSize: "320 MB",
    downloads: 2450000,
    rating: 4.7,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "1.5GB free disk space"],
    features: ["Writer", "Calc", "Impress", "Draw", "Base"],
    downloadLink: "/downloads/libreoffice",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["office", "productivity", "documents", "free"],
  },
  {
    id: "firefox",
    name: "Mozilla Firefox",
    version: "123.0",
    category: "Internet & Network",
    description: "Fast, private, and safe web browser",
    longDescription:
      "Firefox is a free and open-source web browser developed by the Mozilla Foundation. It's known for its speed, privacy features, and customization options.",
    developer: "Mozilla Foundation",
    releaseDate: "2024-02-20",
    fileSize: "58 MB",
    downloads: 3900000,
    rating: 4.7,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "200MB free disk space"],
    features: [
      "Enhanced tracking protection",
      "Private browsing",
      "Sync across devices",
      "Extensions",
      "Picture-in-picture",
    ],
    downloadLink: "/downloads/firefox",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["browser", "internet", "privacy", "free"],
  },
  {
    id: "telegram",
    name: "Telegram Desktop",
    version: "4.16",
    category: "Communication",
    description: "Fast and secure messaging app",
    longDescription: "Telegram is a cloud-based mobile and desktop messaging app with a focus on security and speed.",
    developer: "Telegram FZ-LLC",
    releaseDate: "2024-02-27",
    fileSize: "48 MB",
    downloads: 3600000,
    rating: 4.8,
    license: "Freeware",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "100MB free disk space"],
    features: ["Secret chats", "Cloud storage", "Channels", "Bots", "Voice/video calls"],
    downloadLink: "/downloads/telegram",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["messaging", "chat", "communication", "secure"],
  },
  {
    id: "wireshark",
    name: "Wireshark",
    version: "4.2.3",
    category: "Development",
    description: "Network protocol analyzer",
    longDescription:
      "Wireshark is the world's foremost and widely-used network protocol analyzer. It lets you see what's happening on your network at a microscopic level.",
    developer: "Wireshark Foundation",
    releaseDate: "2024-02-16",
    fileSize: "65 MB",
    downloads: 1280000,
    rating: 4.6,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["2GB RAM", "500MB free disk space"],
    features: ["Deep inspection", "Live capture", "VoIP analysis", "Protocol decryption", "Export data"],
    downloadLink: "/downloads/wireshark",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["network", "analyzer", "development", "free"],
  },
  {
    id: "krita",
    name: "Krita",
    version: "5.2.2",
    category: "Graphics & Design",
    description: "Free and open-source digital painting application",
    longDescription:
      "Krita is a professional FREE and open source painting program. It is made by artists that want to see affordable art tools for everyone.",
    developer: "Krita Foundation",
    releaseDate: "2024-01-26",
    fileSize: "220 MB",
    downloads: 1320000,
    rating: 4.8,
    license: "Free/Open Source",
    operatingSystem: ["Windows", "macOS", "Linux"],
    requirements: ["4GB RAM", "2GB free disk space"],
    features: ["Brush engines", "Layer management", "Animation", "Vector tools", "HDR painting"],
    downloadLink: "/downloads/krita",
    screenshots: ["/placeholder.svg?height=600&width=800"],
    tags: ["painting", "digital art", "graphics", "free"],
  },
]

export function getSoftwareById(id: string): Software | undefined {
  return softwareData.find((software) => software.id === id)
}

export function getLatestSoftware(count = 6): Software[] {
  return [...softwareData]
    .sort((a, b) => new Date(b.releaseDate).getTime() - new Date(a.releaseDate).getTime())
    .slice(0, count)
}

export function getMostDownloaded(count = 6): Software[] {
  return [...softwareData].sort((a, b) => b.downloads - a.downloads).slice(0, count)
}

export function getRecentlyUpdated(count = 6): Software[] {
  return [...softwareData]
    .sort((a, b) => new Date(b.releaseDate).getTime() - new Date(a.releaseDate).getTime())
    .slice(0, count)
}
